// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"], // Connection pooler URL (for queries)
    // Note: DIRECT_URL is read automatically from environment variables during migrations
    // Prisma 7 will use DIRECT_URL env var if present, otherwise falls back to DATABASE_URL
  },
});
